from typing import Dict, Any

from storage import get_user_file, load_json, save_json, today_str


def load_goals_data(username: str) -> Dict[str, Any]:
    """
    Load all goals for a given user from goals.json.
    Structure: { "YYYY-MM-DD": { "summary": str, "feedback": str }, ... }
    """
    path = get_user_file(username, "goals.json")
    return load_json(path, {})


def save_goals_data(username: str, data: Dict[str, Any]) -> None:
    """
    Overwrite the user's goals.json with the given data dict.
    """
    path = get_user_file(username, "goals.json")
    save_json(path, data)


def save_extractor_summary(username: str, date_str: str, summary_json_str: str) -> None:
    """
    Save the extractor's JSON summary into goals.json under this date.
    We simply put the raw JSON string into the 'summary' field for now.
    """
    goals = load_goals_data(username)
    entry = goals.get(date_str, {})
    entry["summary"] = summary_json_str
    # Keep any existing feedback
    entry.setdefault("feedback", "")
    goals[date_str] = entry
    save_goals_data(username, goals)


def load_latest_goal_action(user_state):
    """
    Core logic: load the most recent goal entry for the current user.

    Returns:
        summary:   str (LLM-generated or placeholder)
        feedback:  str (user's editable feedback)
        date_label: str (for UI, e.g. "Date: 2025-01-01" or an error message)
    """
    if not user_state.get("logged_in"):
        # For convenience, we return date_label as an error message here.
        return "", "", "Please log in first."

    username = user_state.get("username")
    goals = load_goals_data(username)

    if not goals:
        # No goals yet: create a placeholder for today
        today = today_str()
        summary = (
            "[Placeholder] Example daily weight loss goal:\n"
            "- Limit total calories to around 1600 kcal\n"
            "- At least 8000 steps of brisk walking or equivalent exercise\n"
            "- Go to bed before 23:00 and get at least 7 hours of sleep\n\n"
            "In the future, this summary will be generated by a local LLM "
            "based on your health profile and progress."
        )
        feedback = ""
        goals[today] = {"summary": summary, "feedback": feedback}
        save_goals_data(username, goals)
        date_label = f"Date: {today}"
        return summary, feedback, date_label

    # There are existing goals: use the latest date (ISO date strings sort correctly)
    latest_date = sorted(goals.keys())[-1]
    entry = goals.get(latest_date, {})
    summary = entry.get("summary", "")
    feedback = entry.get("feedback", "")

    if not summary:
        summary = (
            "[Placeholder] Goal summary is not available yet.\n"
            "In the future, this will be generated by your local LLM."
        )

    date_label = f"Date: {latest_date}"
    return summary, feedback, date_label


def save_goal_feedback_action(
    user_state,
    summary_text: str,
    feedback_text: str,
    date_label: str,
):
    """
    Save user feedback for the currently displayed goal date.
    """
    if not user_state.get("logged_in"):
        return "Please log in first."

    # Parse date from label like 'Date: YYYY-MM-DD'
    if ":" in date_label:
        _, _, tail = date_label.partition(":")
        date_str = tail.strip()
    else:
        date_str = today_str()

    username = user_state.get("username")
    goals = load_goals_data(username)

    # If this date doesn't exist, create it
    entry = goals.get(date_str, {"summary": summary_text or "", "feedback": ""})

    # Ensure summary is stored (if not already present)
    if not entry.get("summary"):
        entry["summary"] = summary_text or ""

    # Always overwrite feedback with the latest text
    entry["feedback"] = feedback_text or ""
    goals[date_str] = entry
    save_goals_data(username, goals)

    return (
        f"Feedback for {date_str} has been saved. "
        "It will be used as part of future prompts for the agent."
    )


def load_goal_summary_for_ui(user_state):
    """
    Small wrapper used by app.py:

    Returns:
        summary_text: str
        feedback_text: str
        date_label:   str
        status_msg:   str (empty if OK, or an error like "Please log in first.")
    """
    summary, feedback, date_label = load_latest_goal_action(user_state)

    # If user not logged in, load_latest_goal_action already wrote
    # "Please log in first." into date_label, so we surface that as status.
    if not user_state.get("logged_in"):
        return "", "", "", "Please log in first."

    # Normal case: no extra status
    return summary, feedback, date_label, ""
